# Generated by Django 4.2.3 on 2023-07-18 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='This is a Lesson.')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='This is a Package.')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='description',
            field=models.TextField(default='This is a Student.'),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='This is a Course')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.lesson')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.package')),
                ('students', models.ManyToManyField(to='student.student')),
            ],
        ),
    ]
