# Generated by Django 4.2.3 on 2023-07-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_lesson_package_student_description_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('nationalcode', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='nationalcode',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
